version: '3.3'

services:
  db:
    image: postgres:14.1-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_HOST: "${POSTGRES_HOST}"
    volumes:
      - ./postgres:/var/lib/postgresql/data
    restart: unless-stopped

  backend:
    ports:
      - "8000:80"
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    restart: unless-stopped
    command: uvicorn sql_app.main:app --host 0.0.0.0 --port 80 --reload

  pg_admin:
    image: dpage/pgadmin4:6.15
    ports:
      - "5050:80"
    environment:
      - GUNICORN_THREADS=1
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      - db
    restart: unless-stopped

  caddy:
    image: caddy:2.6.2-alpine
    restart: unless-stopped
    environment:
      DOMAIN: "${DOMAIN}"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:

